keys:
  - &users age1hdgt7jkjlqs49l6k4tu4vlwk99qrrpcg082n89ljva5smaxscpzqhs29tu
  - &root 24650170F1319CE57856B4D0A2053B74E1C7FC25
creation_rules:
  - key_groups:
    - age:
      - *users
      pgp:
      - *root
