# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ 
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [
    "kvm-amd"
    "amdgpu"
    "i2c_algo_bit"
    "i2c_hid"
    "hid_generic"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_usb_sdmmc"
    ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6ae839fc-7a68-4e53-87cd-1d4dc649c67a";
    fsType = "btrfs";
    options = [ "subvol=@" "compress=none" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6ae839fc-7a68-4e53-87cd-1d4dc649c67a";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=none" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/26EF-E15E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ 
    { device = "/dev/disk/by-uuid/b5a2c261-fb68-4643-8853-7de53398f7ee"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
